spring:

  application:

    name: uploadexcel-service



  jpa: 

    database: mysql

    show-sql: true

    hibernate: 

      ddl-auto: update

    properties:

      hibernate: 

        dialect: org.hibernate.dialect.MySQL5InnoDBDialect



  #a数据库连接配置

  datasource:

    driver-class-name: com.mysql.jdbc.Driver

    url: jdbc:mysql://localhost:3306/smc?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8

    username: root

    password: jul18sat



  profiles:  

    active: dev



server:

  port: 8004



---

spring:

  profiles: dev



#eureka settings

eureka:

  client:

    service-url:

      defaultZone: http://127.0.0.1:8761/eureka/

    healthcheck:

      enabled: true

  instance:

    lease-expiration-duration-in-seconds: 30

    lease-renewal-interval-in-seconds: 10



---

spring:

  profiles: prod



#eureka settings     

eureka:

  client:

    service-url:

      defaultZone: http://106.54.194.33:8761/eureka/

    healthcheck:

      enabled: true

  instance:

    lease-expiration-duration-in-seconds: 30

    lease-renewal-interval-in-seconds: 10